import sqlite3


conn = sqlite3.connect('database.db')
c = conn.cursor()

# suppression des données de la tables
# conn.execute("DELETE from article")
# conn.commit()


# Insertion des articles
articles = [
    ('Comment devenir un expert en programmation', 'devenir-un-expert-en-programmation', 'Paul Dupont', '2023-02-15', 'Si vous voulez devenir un expert en programmation, il est important de suivre une formation complète et de pratiquer régulièrement. Commencez par apprendre les bases de la programmation, puis plongez-vous dans des projets pratiques pour mettre en pratique vos compétences. Trouvez une communauté de programmeurs avec laquelle vous pourrez échanger et obtenir des conseils. Enfin, tenez-vous informé des dernières tendances et technologies en programmation pour rester à la pointe du domaine.'),
    ('Les avantages de la méditation quotidienne', 'avantages-meditation-quotidienne', 'Sophie Martin', '2023-04-02', 'La méditation quotidienne peut apporter de nombreux avantages pour la santé mentale et physique. Elle peut aider à réduire le stress, améliorer la concentration et la créativité, et renforcer le système immunitaire. Pour commencer à méditer, trouvez un endroit calme et confortable où vous pourrez vous détendre. Concentrez-vous sur votre respiration et essayez de calmer votre esprit en observant vos pensées sans les juger.'),
    ('Les bienfaits du yoga sur la santé', 'bienfaits-yoga-sante', 'Marc Rousseau', '2023-05-01', "Le yoga est une pratique qui peut apporter de nombreux bienfaits pour la santé physique et mentale. Il peut aider à améliorer la souplesse, renforcer les muscles et réduire le stress et l'anxiété. Pour commencer à pratiquer le yoga, trouvez un cours ou un instructeur qualifié pour vous guider dans les poses et les techniques de respiration. Pratiquez régulièrement pour en tirer les bienfaits maximum."),
    ('Les meilleurs conseils pour un régime alimentaire équilibré', 'conseils-regime-alimentaire-equilibre', 'Alice Girard', '2023-06-12', "Pour maintenir un régime alimentaire équilibré, il est important de consommer une variété d'aliments sains dans les bonnes proportions. Les fruits et légumes frais, les protéines maigres et les grains entiers devraient constituer la majeure partie de votre alimentation, tandis que les aliments transformés et riches en matières grasses et en sucre devraient être consommés avec modération. Évitez les régimes à la mode qui promettent des résultats rapides et optez pour une alimentation saine et équilibrée à long terme."),
    ('Les secrets pour améliorer votre mémoire', 'secrets-ameliorer-memoire', 'David Leclerc', '2023-01-20', 'Si vous voulez améliorer votre mémoire, il est important de pratiquer des exercices mentaux régulièrement.'),
    ('Les bienfaits de la randonnée en montagne', 'bienfaits-randonnee-montagne', 'Marie Durand', '2023-08-05', "La randonnée en montagne est une activité physique bénéfique pour la santé et l'esprit. Elle peut aider à améliorer la condition physique, à réduire le stress et à renforcer le sentiment de communauté. Pour profiter pleinement de la randonnée, il est important de se préparer adéquatement, d'apporter suffisamment d'eau et de nourriture, et de suivre les règles de sécurité en montagne."),
    ("Comment trouver l'inspiration pour écrire", 'trouver-inspiration-ecrire', 'Jeanne Martin', '2023-09-15', "Trouver l'inspiration pour écrire peut être difficile, mais il existe plusieurs techniques qui peuvent aider. Essayez de vous libérer l'esprit en faisant de l'exercice, en pratiquant la méditation ou en faisant quelque chose de créatif. Prenez des notes sur vos idées et vos pensées tout au long de la journée, et lisez et écrivez régulièrement pour stimuler votre créativité."),
    ('Les bienfaits de la musculation pour les femmes', 'bienfaits-musculation-femmes', 'Lucie Tremblay', '2022-10-03', "La musculation peut offrir de nombreux avantages pour les femmes, notamment la perte de poids, la tonification musculaire et la prévention de l'ostéoporose. Pour commencer à faire de la musculation, il est important de trouver un programme d'entraînement adapté à vos besoins et à votre niveau de condition physique. N'oubliez pas de vous reposer suffisamment entre les séances pour permettre à vos muscles de récupérer."),
    ("Les bienfaits de l'apprentissage continu", 'bienfaits-apprentissage-continu', 'Alexandre Lavoie', '2023-03-02', "L'apprentissage continu peut aider à stimuler le cerveau, à améliorer les compétences et à augmenter les perspectives de carrière. Il existe de nombreuses façons de continuer à apprendre tout au long de la vie, notamment en suivant des cours en ligne, en lisant des livres et en participant à des formations en entreprise. N'oubliez pas de trouver des sujets qui vous intéressent pour rendre l'apprentissage plus agréable."),
    ("Les avantages de l'éducation musicale pour les enfants", 'avantages-education-musicale-enfants', 'Sophie Boucher', '2022-12-12', "L'éducation musicale peut aider les enfants à développer leur créativité, leur coordination et leur confiance en soi. Elle peut également améliorer les compétences linguistiques et mathématiques. Pour offrir à vos enfants les avantages de l'éducation musicale, cherchez des programmes d'éducation musicale dans votre communauté ou investissez dans des instruments pour votre maison."),
    ('Les avantages de la lecture', 'avantages-lecture', 'Marie Dupont', '2023-08-12', 'La lecture est une activité bénéfique pour le développement personnel et la santé mentale. Elle peut aider à réduire le stress, améliorer la concentration et la créativité, et renforcer les capacités cognitives. Pour commencer à lire, choisissez un livre qui vous intéresse et trouvez un endroit calme où vous pourrez vous concentrer. Essayez de lire régulièrement pour en tirer les bienfaits maximum.'),
    ('Comment améliorer sa productivité au travail', 'ameliorer-productivite-travail', 'Jean Martin', '2023-02-03', "Pour améliorer sa productivité au travail, il est important de planifier ses tâches, de fixer des objectifs réalistes et de se concentrer sur les tâches les plus importantes en premier. Évitez les distractions comme les réseaux sociaux et les e-mails non urgents. Prenez des pauses régulières pour éviter la fatigue et le surmenage."),
    ("Les bienfaits de l'exercice physique pour la santé", "bienfaits-exercice-physique-sante", 'Sophie Leclerc', '2023-10-11', "L'exercice physique régulier peut aider à prévenir de nombreuses maladies et améliorer la santé physique et mentale. Il peut aider à réduire le risque de maladies cardiaques, d'obésité et de diabète, et améliorer la qualité du sommeil et l'humeur. Pour commencer à faire de l'exercice, choisissez une activité que vous appréciez et trouvez un partenaire d'entraînement pour rester motivé."),
    ("Les secrets d'une vie heureuse et épanouissante", 'secrets-vie-heureuse-epanouissante', 'David Dupuis', '2023-11-24', "Pour mener une vie heureuse et épanouissante, il est important de se concentrer sur les choses qui comptent vraiment dans la vie, comme les relations, les expériences et les passions. Évitez de vous comparer aux autres et apprenez à apprécier ce que vous avez. Prenez soin de votre santé mentale et physique et prenez le temps de vous reposer et de vous détendre."),
    ('Les bienfaits de la musique sur la santé mentale', 'bienfaits-musique-sante-mentale', 'Marie Martin', '2023-01-07', "La musique peut avoir des effets bénéfiques sur la santé mentale en aidant à réduire le stress et l'anxiété, améliorer l'humeur et la créativité, et renforcer la mémoire et la cognition. Pour bénéficier de ces bienfaits, écoutez de la musique régulièrement et essayez de jouer d'un instrument ou de chanter.")
]

for article in articles :
    conn.execute("INSERT INTO article (titre, identifiant, auteur, date_publication, paragraphe) VALUES (?, ?, ?, ?, ?)", article)

conn.commit()
conn.close()